# Generated by Django 3.1.3 on 2022-01-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_student_id', models.IntegerField(blank=True, null=True)),
                ('payer', models.CharField(blank=True, max_length=40, null=True)),
                ('brother_dc_yn', models.CharField(default='n', max_length=1)),
                ('recommend_dc_start', models.CharField(blank=True, max_length=6, null=True)),
                ('recommend_dc_end', models.CharField(blank=True, max_length=6, null=True)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('y6', 'Year 6'), ('y7', 'Year 7'), ('e1', 'Elementary 1'), ('e2', 'Elementary 2'), ('e3', 'Elementary 3'), ('e4', 'Elementary 4'), ('e5', 'Elementary 5'), ('e6', 'Elementary 6')], max_length=2)),
                ('sugang_type', models.CharField(choices=[('d3', 'Day3'), ('d4', 'Day4')], max_length=2)),
                ('price', models.IntegerField()),
                ('refund', models.IntegerField()),
                ('start_mt', models.CharField(default='yyyymm', max_length=6)),
                ('end_mt', models.CharField(default='999912', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('y6', 'Year 6'), ('y7', 'Year 7'), ('e1', 'Elementary 1'), ('e2', 'Elementary 2'), ('e3', 'Elementary 3'), ('e4', 'Elementary 4'), ('e5', 'Elementary 5'), ('e6', 'Elementary 6')], max_length=2)),
                ('create_date', models.DateTimeField()),
                ('delete_yn', models.CharField(default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sugang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(choices=[('c1', 'Mikyoung'), ('c2', 'Aekyoung')], max_length=2)),
                ('weekday', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('time', models.CharField(max_length=1)),
                ('start_mt', models.CharField(default='yyyymmdd', max_length=6)),
                ('end_mt', models.CharField(default='999912', max_length=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom.student')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.CharField(default='yyyymmddhhmmss', max_length=14)),
                ('pay_amt', models.IntegerField()),
                ('payer', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_status', models.CharField(choices=[('OP', 'Open'), ('CO', 'Close')], max_length=2)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyroom.account')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_status', models.CharField(choices=[('OP', 'Open'), ('FP', 'Full Payment'), ('PP', 'Partial Payment')], max_length=2)),
                ('bill_mt', models.CharField(max_length=6)),
                ('bill_amt', models.IntegerField(blank=True, null=True)),
                ('base_amt', models.IntegerField(blank=True, null=True)),
                ('refund_amt', models.IntegerField(blank=True, null=True)),
                ('brother_dc_amt', models.IntegerField(blank=True, null=True)),
                ('recommend_dc_amt', models.IntegerField(blank=True, null=True)),
                ('pay_amt', models.IntegerField(blank=True, null=True)),
                ('pay_type', models.CharField(blank=True, choices=[('p1', 'Kimpopay'), ('p2', 'Accounttransfer')], max_length=2, null=True)),
                ('pay_dt', models.CharField(blank=True, max_length=8, null=True)),
                ('pay_id', models.IntegerField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom.student'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_dt', models.CharField(default='yyyymmdd', max_length=8)),
                ('absence_detail', models.TextField(default='결석사유:')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom.student')),
            ],
        ),
    ]
