# Generated by Django 3.1.3 on 2022-01-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payer_phone_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
