# Generated by Django 3.1.3 on 2022-01-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0002_account_payer_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
