# Generated by Django 3.1.3 on 2022-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0003_auto_20220127_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
