# Generated by Django 3.1.3 on 2022-01-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0004_auto_20220127_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugang',
            name='start_mt',
            field=models.CharField(default='yyyymm', max_length=6),
        ),
        migrations.AlterField(
            model_name='sugang',
            name='time',
            field=models.CharField(choices=[('1', 'One Oclock'), ('2', 'Two Oclock'), ('3', 'Three Oclock'), ('4', 'Four Oclock'), ('5', 'Five Oclock')], max_length=1),
        ),
    ]
