# Generated by Django 3.1.3 on 2022-01-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0005_auto_20220127_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='recommend_dc_end',
            field=models.CharField(blank=True, default='yyyymm', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='recommend_dc_start',
            field=models.CharField(blank=True, default='yyyymm', max_length=6, null=True),
        ),
    ]
