# Generated by Django 3.1.3 on 2022-01-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0006_auto_20220128_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='brother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studyroom.student'),
        ),
    ]
