# Generated by Django 3.1.3 on 2022-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0011_auto_20220128_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='brother_base_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='brother_refund_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='brother_dc_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('KP', 'Kimpopay'), ('AT', 'Accounttransfer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='recommend_dc_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='refund_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='grade',
            field=models.CharField(choices=[('Y6', 'Year 6'), ('Y7', 'Year 7'), ('E1', 'Elementary 1'), ('E2', 'Elementary 2'), ('E3', 'Elementary 3'), ('E4', 'Elementary 4'), ('E5', 'Elementary 5'), ('E6', 'Elementary 6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='sugang_type',
            field=models.CharField(choices=[('D3', 'Day3'), ('D4', 'Day4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Y6', 'Year 6'), ('Y7', 'Year 7'), ('E1', 'Elementary 1'), ('E2', 'Elementary 2'), ('E3', 'Elementary 3'), ('E4', 'Elementary 4'), ('E5', 'Elementary 5'), ('E6', 'Elementary 6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sugang',
            name='class_id',
            field=models.CharField(choices=[('MK', 'Mikyoung'), ('AK', 'Aekyoung')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sugang',
            name='weekday',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3),
        ),
    ]
