# Generated by Django 3.1.3 on 2022-02-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0012_auto_20220130_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_type',
            field=models.CharField(choices=[('KP', '김포페이'), ('AT', '계좌이체')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(choices=[('OP', '발행'), ('FP', '완납'), ('PP', '부분납')], max_length=2),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('KP', '김포페이'), ('AT', '계좌이체')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_status',
            field=models.CharField(choices=[('OP', '등록'), ('CO', 'Close')], max_length=2),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='grade',
            field=models.CharField(choices=[('Y6', '6세'), ('Y7', '7세'), ('E1', '1학년'), ('E2', '2학년'), ('E3', '3학년'), ('E4', '4학년'), ('E5', '5학년'), ('E6', '6학년')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Y6', '6세'), ('Y7', '7세'), ('E1', '1학년'), ('E2', '2학년'), ('E3', '3학년'), ('E4', '4학년'), ('E5', '5학년'), ('E6', '6학년')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sugang',
            name='class_id',
            field=models.CharField(choices=[('MK', '심미경'), ('AK', '심애경')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sugang',
            name='time',
            field=models.CharField(choices=[('1', '1시'), ('2', '2시'), ('3', '3시'), ('4', '4시'), ('5', '5시')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sugang',
            name='weekday',
            field=models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일')], max_length=3),
        ),
    ]
