# Generated by Django 3.1.3 on 2022-02-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0014_auto_20220209_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sms_phone_num',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smstype', models.CharField(max_length=3)),
                ('to', models.CharField(max_length=11)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(max_length=2000)),
                ('requestId', models.CharField(blank=True, max_length=32, null=True)),
                ('requestTime', models.CharField(blank=True, max_length=50, null=True)),
                ('statusCode', models.CharField(blank=True, choices=[('200', 'OK'), ('202', 'Accept'), ('400', 'Bad Request'), ('401', 'Unauthorized'), ('403', 'Forbidden'), ('404', 'Not Found'), ('429', 'Too Many Requests'), ('500', 'Internal Server Error')], max_length=3, null=True)),
                ('statusName', models.CharField(blank=True, max_length=10, null=True)),
                ('messageId', models.CharField(blank=True, max_length=23, null=True)),
                ('create_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom.account')),
            ],
        ),
    ]
