# Generated by Django 3.1.3 on 2022-02-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0015_auto_20220211_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='sub_student_id',
        ),
    ]
