# Generated by Django 3.1.3 on 2022-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0016_remove_account_sub_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='messageStatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
