# Generated by Django 3.1.3 on 2022-02-13 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0017_sms_messagestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='brother_dc_yn',
        ),
    ]
