# Generated by Django 3.1.3 on 2022-02-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0019_auto_20220213_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studyroom.account'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_status',
            field=models.CharField(choices=[('OP', '미연결'), ('CO', '연결')], max_length=2),
        ),
    ]
